use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true, :warn_for_unused_master_specs_repo => false

platform :ios, '13.0'

target 'TEMPLATE_POD_SWIFT_Example' do
  pod 'TEMPLATE_POD_SWIFT', :path => '../'

  target 'TEMPLATE_POD_SWIFT_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
