platform :ios, '14.0'
use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true, :warn_for_unused_master_specs_repo => false

target 'TEMPLATE_IOS_SWIFTUI' do
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
